language: node_js
node_js:
- '8'
dist: trusty
sudo: false
install:
- npm install
script:
- npm run code-check
- npm run test
- npm run build
deploy:
  provider: npm
  email: TrdelnikSquad@cimpress.com
  skip_cleanup: true
  api_key:
    secure: UDHF8UlT666etc1kGYPdRtX9+BF+f77jV/+hRCOTujTgbz+LvKNX9dVQi+n5pAyaUn2fVLR5gUhY8qBdU4fsC7za+yi+JUKWFxw4yG9zfy3IZn9He4P6T6Wmvdfhibyg7+/E56NAAhNltqYZOQpiagTYGm0bslYgZY0OfSqaTHv8vYVndFCnw8dyjsLA27kWkIW+EHvTKSGmsCaDol4OzTpHE7TiWPj/SErszjE/gauEpumu++iTV1B3Tt9F7HbM2qiZ55Ghgw5jTXJsEovxQNMlXRfvVtKLeuozthQzu/xkIS1GD1hyBjNESqZJOzrrUDzUBs3AjoSenBfPqsTxeGf9aQaUy/MyeLnjvlyMum7kO7iUItJQUxQBR68qrd9TRtNhAI+7sGwbdCDtVjeVfvgGJwvC+0T8OtK+z2csMV7AJ3AFvLsLbTARXZXTccmWZeoj3L4e1BJE4UXrKvbZFR4JjaS57Rh7pm7wGspvJEM3dPeAOhSv8K9ohU7P2SaMQgBQFigmQTDuOxaEzs8UGpWtuKhB4QljMVu7806L4dvFzcoTBsLIvtlvkTsbomP1ko2w/4mzT1o0OiqzymnWapm6eT4qEExN07vt0zeGIVbg/vI8sS8ZSMn9BaSP30sEW4ghXoFtdVOVNj9PjuU7G/kC0CiMlSr7XGCgdBIIuFI=
  on:
    branch: master
    repo: Cimpress/coam-client
